name: Live Infrastructure CI/CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'dev/**'
      - 'stage/**'
      - 'prod/**'
      - 'terragrunt.hcl'
  pull_request:
    branches: [ main ]
    paths: 
      - 'dev/**'
      - 'stage/**'
      - 'prod/**'
      - 'terragrunt.hcl'

env:
  TERRAGRUNT_VERSION: '0.58.7'
  TERRAFORM_VERSION: '1.5.7'

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      dev-changed: ${{ steps.changes.outputs.dev }}
      stage-changed: ${{ steps.changes.outputs.stage }}
      prod-changed: ${{ steps.changes.outputs.prod }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect changes
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -E '^dev/'; then
            echo "dev=true" >> $GITHUB_OUTPUT
          else
            echo "dev=false" >> $GITHUB_OUTPUT
          fi
          
          if git diff --name-only HEAD~1 HEAD | grep -E '^stage/'; then
            echo "stage=true" >> $GITHUB_OUTPUT
          else
            echo "stage=false" >> $GITHUB_OUTPUT
          fi
          
          if git diff --name-only HEAD~1 HEAD | grep -E '^prod/'; then
            echo "prod=true" >> $GITHUB_OUTPUT
          else
            echo "prod=false" >> $GITHUB_OUTPUT
          fi

  dev:
    name: Development Environment
    needs: detect-changes
    if: needs.detect-changes.outputs.dev-changed == 'true'
    uses: melorga/gha-workflows/.github/workflows/terragrunt.yml@main
    with:
      terragrunt_version: '0.58.7'
      terraform_version: '1.5.7'
      working_directory: './dev/us-east-1'
      environment: 'development'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

  stage:
    name: Staging Environment
    needs: [detect-changes, dev]
    if: needs.detect-changes.outputs.stage-changed == 'true' && (success() || needs.dev.result == 'skipped')
    uses: melorga/gha-workflows/.github/workflows/terragrunt.yml@main
    with:
      terragrunt_version: '0.58.7'
      terraform_version: '1.5.7'
      working_directory: './stage/us-east-1'
      environment: 'staging'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

  prod:
    name: Production Environment
    needs: [detect-changes, stage]
    if: needs.detect-changes.outputs.prod-changed == 'true' && (success() || needs.stage.result == 'skipped')
    uses: melorga/gha-workflows/.github/workflows/terragrunt.yml@main
    with:
      terragrunt_version: '0.58.7'
      terraform_version: '1.5.7'
      working_directory: './prod/us-east-1'
      environment: 'production'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
